osx_image: xcode8
language: objective-c
before_install:
  - gem install cocoapods xcpretty slather -N
  - pod update Firebase
podfile: Podfile
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
install:
  - ./firebase_init.sh
script:
- set -o pipefail && xcodebuild -workspace TimeTracker.xcworkspace
  -scheme TimeTracker -sdk iphonesimulator10.0 -destination "platform=iOS Simulator,name=iPhone 6,OS=10.0" GCC_GENERATE_TEST_COVERAGE_FILES=YES clean build test | xcpretty
